pluginManagement {
    repositories {
        maven { url "https://maven.google.com" }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url "https://maven.google.com" }
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
    }
}
include ':app', ':imageeditlibrary'
